name: Release

on:
  workflow_dispatch:
    inputs:
      pkgrel:
        description: 'Package release (12345.X)'
        required: false
        default: '1'

jobs:
  release-hearthstone-data-job:
    runs-on: ubuntu-latest
    name: Release hearthstone-data
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get -y install libxml2-utils
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: pip install wheel setuptools==60
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: Build
      run: python setup.py sdist bdist_wheel
      env:
        PKGREL: ${{ github.event.inputs.pkgrel }}
    - name: Upload to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
